### ISSUE TITLE
Add project description and goals to the README.md

### ISSUE THREAD

**Issue by newoga** [jalawelo/math-problem-generator#1]
I initialized the repository with a `README.md`. We should add the project description and goals to it for the time being.

**Comment by mgspross** [comment]
@newoga: I updated the README file. I intentionally wrote it as if the program already exists so that it can serve as both _de facto_ high-level requirements for us and still make sense once we have actually have a working version of the program.

Of course, we can still add to or edit the README as the project progresses.
