### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by newoga** [jalawelo/math-problem-generator#2]
We should create a `CONTRIBUTING.md` as well that outlines our basic process. @mgspross and I decided that contributors should work off of forks.

**Comment by mgspross** [comment]
@newoga: Since this is assigned to you, just a heads up to also edit [the **Contributing** section](https://github.com/jalawelo/math-problem-generator/blob/4308e4319cfc168a6cf844e2dc5ff7eaa4928f94/README.md#contributing) in the README when you create the `CONTRIBUTING.md` file, since it currently has placeholder note saying we're working on a `CONTRIBUTING.md` file.

Specifically, I'd recommend doing the following alongside writing up the `CONTRIBUTING.md` file:

- Look at the  [the **Contributing** section](https://github.com/jalawelo/math-problem-generator/blob/4308e4319cfc168a6cf844e2dc5ff7eaa4928f94/README.md#contributing) in the README to see if you want move any information there into the `CONTRIBUTING.md` file.
- Remove the note about us working on a `CONTRIBUTING.md` file.
- Either remove the **Contributing** section in the README altogether, or replace/amend the body of that section with a link to the `CONTRIBUTING.md` file.
